# Generated by Django 6.0 on 2025-12-30 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
