name: Deploy Django to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Получить код
      uses: actions/checkout@v4

    - name: 🔑 Настроить SSH доступ
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: 🚀 Задеплоить на сервер
      run: |
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
          cd /var/www/django4
          git pull origin main
          python3 -m venv venv
          source venv/bin/activate
          pip install Django==4.2.10 gunicorn
          python manage.py migrate
          pkill -f gunicorn || true
          nohup gunicorn config.wsgi:application --bind 0.0.0.0:8000 > server.log 2>&1 &
        